apiVersion: v2
name: idpay-merchant
description: IDPay Merchant
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: microservice-chart
    version: 1.20.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"